#!/usr/bin/env/fish

set workspace "$HOME/workspace"
set perspace  "$HOME/perspace"

set projects $(find "$workspace" "$perspace" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)

set selection $(printf '%s\n' $projects | fzf --prompt "Choose the project to use")


if test -z $selection
	exit 0
end

set base (basename $selection)


if tmux has -t "$base" 2>/dev/null
	if test "$TERM_PROGRAM" = "tmux"
		tmux switchc -t "$base"
	else
		tmux a -t "$base"
	end
else
	if test "$TERM_PROGRAM" = "tmux"
		tmux new-session -d -s "$base" -c "$selection"
		tmux switchc -t "$base"
	else
		tmux new-session -A -s "$base" -c "$selection"
	end
end
stty sane 
exit 0
